-- INSERÇÃO DE DADOS INICIAIS PARA A TABELA ROLES
INSERT INTO ROLES (ID, DESCRIPTION) VALUES (UUID_TO_BIN(UUID()), 'USER');
INSERT INTO ROLES (ID, DESCRIPTION) VALUES (UUID_TO_BIN(UUID()), 'MODERATOR');
INSERT INTO ROLES (ID, DESCRIPTION) VALUES (UUID_TO_BIN(UUID()), 'ADMINISTRATOR');