-- CRIAÇÃO DA TABELA "PREFERÊNCIAS DE USUÁRIOS"
CREATE TABLE IF NOT EXISTS USER_PREFERENCES
(
    ID BINARY(16) NOT NULL PRIMARY KEY,
    PREFERENCE_KEY VARCHAR(50) NOT NULL,
    VALUE VARCHAR(120)
);
